### ISSUE TITLE
Large memory usage during tests causes OOM

### ISSUE THREAD

**Issue by piotrtomiak** [JetBrains/debugger-agent#10]
It looks like there is something wrong with `CaptureStorage`, as it grows too much during tests, where there are a lot of coroutines invoked. Is it possible that the old stack traces are not removed?
<img width="1468" alt="Snapshots  - YourKit Java Profiler 2024 3-b161 2024-11-19 14-38-37" src="https://github.com/user-attachments/assets/db23f74e-dcb2-481e-8cda-0b99c1352240">

**Comment by gorrus** [comment]
should be fixed already within [IDEA-360126](https://youtrack.jetbrains.com/issue/IDEA-360126) Memory leak in com.intellij.rt.debugger.agent.CaptureStorage.ConcurrentIdentityWeakHashMap
